// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package raft.transport

@SerialVersionUID(0L)
final case class AppendEntriesResponse(
    success: _root_.scala.Boolean = false,
    term: _root_.scala.Long = 0L,
    currentLogIndex: _root_.scala.Long = 0L,
    commitIndex: _root_.scala.Long = 0L,
    nodeId: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[AppendEntriesResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = success
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(1, __value)
        }
      };
      
      {
        val __value = term
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(2, __value)
        }
      };
      
      {
        val __value = currentLogIndex
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(3, __value)
        }
      };
      
      {
        val __value = commitIndex
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(4, __value)
        }
      };
      
      {
        val __value = nodeId
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = success
        if (__v != false) {
          _output__.writeBool(1, __v)
        }
      };
      {
        val __v = term
        if (__v != 0L) {
          _output__.writeInt64(2, __v)
        }
      };
      {
        val __v = currentLogIndex
        if (__v != 0L) {
          _output__.writeInt64(3, __v)
        }
      };
      {
        val __v = commitIndex
        if (__v != 0L) {
          _output__.writeInt64(4, __v)
        }
      };
      {
        val __v = nodeId
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withSuccess(__v: _root_.scala.Boolean): AppendEntriesResponse = copy(success = __v)
    def withTerm(__v: _root_.scala.Long): AppendEntriesResponse = copy(term = __v)
    def withCurrentLogIndex(__v: _root_.scala.Long): AppendEntriesResponse = copy(currentLogIndex = __v)
    def withCommitIndex(__v: _root_.scala.Long): AppendEntriesResponse = copy(commitIndex = __v)
    def withNodeId(__v: _root_.scala.Predef.String): AppendEntriesResponse = copy(nodeId = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = success
          if (__t != false) __t else null
        }
        case 2 => {
          val __t = term
          if (__t != 0L) __t else null
        }
        case 3 => {
          val __t = currentLogIndex
          if (__t != 0L) __t else null
        }
        case 4 => {
          val __t = commitIndex
          if (__t != 0L) __t else null
        }
        case 5 => {
          val __t = nodeId
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PBoolean(success)
        case 2 => _root_.scalapb.descriptors.PLong(term)
        case 3 => _root_.scalapb.descriptors.PLong(currentLogIndex)
        case 4 => _root_.scalapb.descriptors.PLong(commitIndex)
        case 5 => _root_.scalapb.descriptors.PString(nodeId)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: raft.transport.AppendEntriesResponse.type = raft.transport.AppendEntriesResponse
    // @@protoc_insertion_point(GeneratedMessage[raft.transport.AppendEntriesResponse])
}

object AppendEntriesResponse extends scalapb.GeneratedMessageCompanion[raft.transport.AppendEntriesResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[raft.transport.AppendEntriesResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): raft.transport.AppendEntriesResponse = {
    var __success: _root_.scala.Boolean = false
    var __term: _root_.scala.Long = 0L
    var __currentLogIndex: _root_.scala.Long = 0L
    var __commitIndex: _root_.scala.Long = 0L
    var __nodeId: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __success = _input__.readBool()
        case 16 =>
          __term = _input__.readInt64()
        case 24 =>
          __currentLogIndex = _input__.readInt64()
        case 32 =>
          __commitIndex = _input__.readInt64()
        case 42 =>
          __nodeId = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    raft.transport.AppendEntriesResponse(
        success = __success,
        term = __term,
        currentLogIndex = __currentLogIndex,
        commitIndex = __commitIndex,
        nodeId = __nodeId,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[raft.transport.AppendEntriesResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      raft.transport.AppendEntriesResponse(
        success = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        term = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        currentLogIndex = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        commitIndex = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        nodeId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = RaftProto.javaDescriptor.getMessageTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = RaftProto.scalaDescriptor.messages(5)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = raft.transport.AppendEntriesResponse(
    success = false,
    term = 0L,
    currentLogIndex = 0L,
    commitIndex = 0L,
    nodeId = ""
  )
  implicit class AppendEntriesResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, raft.transport.AppendEntriesResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, raft.transport.AppendEntriesResponse](_l) {
    def success: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.success)((c_, f_) => c_.copy(success = f_))
    def term: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.term)((c_, f_) => c_.copy(term = f_))
    def currentLogIndex: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.currentLogIndex)((c_, f_) => c_.copy(currentLogIndex = f_))
    def commitIndex: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.commitIndex)((c_, f_) => c_.copy(commitIndex = f_))
    def nodeId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.nodeId)((c_, f_) => c_.copy(nodeId = f_))
  }
  final val SUCCESS_FIELD_NUMBER = 1
  final val TERM_FIELD_NUMBER = 2
  final val CURRENTLOGINDEX_FIELD_NUMBER = 3
  final val COMMITINDEX_FIELD_NUMBER = 4
  final val NODEID_FIELD_NUMBER = 5
  def of(
    success: _root_.scala.Boolean,
    term: _root_.scala.Long,
    currentLogIndex: _root_.scala.Long,
    commitIndex: _root_.scala.Long,
    nodeId: _root_.scala.Predef.String
  ): _root_.raft.transport.AppendEntriesResponse = _root_.raft.transport.AppendEntriesResponse(
    success,
    term,
    currentLogIndex,
    commitIndex,
    nodeId
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[raft.transport.AppendEntriesResponse])
}
