// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package raft.transport

@SerialVersionUID(0L)
final case class Command(
    cmdType: _root_.scala.Predef.String = "",
    op: _root_.scala.Predef.String = "",
    key: _root_.scala.Predef.String = "",
    value: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Command] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = cmdType
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = op
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = key
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = value
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = cmdType
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = op
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = key
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = value
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withCmdType(__v: _root_.scala.Predef.String): Command = copy(cmdType = __v)
    def withOp(__v: _root_.scala.Predef.String): Command = copy(op = __v)
    def withKey(__v: _root_.scala.Predef.String): Command = copy(key = __v)
    def withValue(__v: _root_.scala.Predef.String): Command = copy(value = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = cmdType
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = op
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = key
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = value
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(cmdType)
        case 2 => _root_.scalapb.descriptors.PString(op)
        case 3 => _root_.scalapb.descriptors.PString(key)
        case 4 => _root_.scalapb.descriptors.PString(value)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: raft.transport.Command.type = raft.transport.Command
    // @@protoc_insertion_point(GeneratedMessage[raft.transport.Command])
}

object Command extends scalapb.GeneratedMessageCompanion[raft.transport.Command] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[raft.transport.Command] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): raft.transport.Command = {
    var __cmdType: _root_.scala.Predef.String = ""
    var __op: _root_.scala.Predef.String = ""
    var __key: _root_.scala.Predef.String = ""
    var __value: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __cmdType = _input__.readStringRequireUtf8()
        case 18 =>
          __op = _input__.readStringRequireUtf8()
        case 26 =>
          __key = _input__.readStringRequireUtf8()
        case 34 =>
          __value = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    raft.transport.Command(
        cmdType = __cmdType,
        op = __op,
        key = __key,
        value = __value,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[raft.transport.Command] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      raft.transport.Command(
        cmdType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        op = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = RaftProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = RaftProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = raft.transport.Command(
    cmdType = "",
    op = "",
    key = "",
    value = ""
  )
  implicit class CommandLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, raft.transport.Command]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, raft.transport.Command](_l) {
    def cmdType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.cmdType)((c_, f_) => c_.copy(cmdType = f_))
    def op: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.op)((c_, f_) => c_.copy(op = f_))
    def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
    def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.value)((c_, f_) => c_.copy(value = f_))
  }
  final val CMDTYPE_FIELD_NUMBER = 1
  final val OP_FIELD_NUMBER = 2
  final val KEY_FIELD_NUMBER = 3
  final val VALUE_FIELD_NUMBER = 4
  def of(
    cmdType: _root_.scala.Predef.String,
    op: _root_.scala.Predef.String,
    key: _root_.scala.Predef.String,
    value: _root_.scala.Predef.String
  ): _root_.raft.transport.Command = _root_.raft.transport.Command(
    cmdType,
    op,
    key,
    value
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[raft.transport.Command])
}
