// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package raft.transport

object RaftProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq.empty
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      raft.transport.Command,
      raft.transport.LogEntry,
      raft.transport.RequestVoteRequest,
      raft.transport.AppendEntriesRequest,
      raft.transport.RequestVoteResponse,
      raft.transport.AppendEntriesResponse
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CgpyYWZ0LnByb3RvEg5yYWZ0LnRyYW5zcG9ydCKIAQoHQ29tbWFuZBImCgdjbWRUeXBlGAEgASgJQgziPwkSB2NtZFR5cGVSB
  2NtZFR5cGUSFwoCb3AYAiABKAlCB+I/BBICb3BSAm9wEhoKA2tleRgDIAEoCUII4j8FEgNrZXlSA2tleRIgCgV2YWx1ZRgEIAEoC
  UIK4j8HEgV2YWx1ZVIFdmFsdWUirgEKCExvZ0VudHJ5Eh0KBHRlcm0YASABKANCCeI/BhIEdGVybVIEdGVybRIgCgVpbmRleBgCI
  AEoA0IK4j8HEgVpbmRleFIFaW5kZXgSLAoJdGltZXN0YW1wGAMgASgJQg7iPwsSCXRpbWVzdGFtcFIJdGltZXN0YW1wEjMKA2NtZ
  BgEIAEoCzIXLnJhZnQudHJhbnNwb3J0LkNvbW1hbmRCCOI/BRIDY21kUgNjbWQi0gEKElJlcXVlc3RWb3RlUmVxdWVzdBIdCgR0Z
  XJtGAEgASgDQgniPwYSBHRlcm1SBHRlcm0SNQoMbGFzdExvZ0luZGV4GAIgASgDQhHiPw4SDGxhc3RMb2dJbmRleFIMbGFzdExvZ
  0luZGV4EjIKC2xhc3RMb2dUZXJtGAMgASgDQhDiPw0SC2xhc3RMb2dUZXJtUgtsYXN0TG9nVGVybRIyCgtjYW5kaWNhdGVJZBgEI
  AEoCUIQ4j8NEgtjYW5kaWNhdGVJZFILY2FuZGljYXRlSWQixAIKFEFwcGVuZEVudHJpZXNSZXF1ZXN0Eh0KBHRlcm0YASABKANCC
  eI/BhIEdGVybVIEdGVybRIyCgtwcmV2TG9nVHJlbRgCIAEoA0IQ4j8NEgtwcmV2TG9nVHJlbVILcHJldkxvZ1RyZW0SNQoMcHJld
  kxvZ0luZGV4GAMgASgDQhHiPw4SDHByZXZMb2dJbmRleFIMcHJldkxvZ0luZGV4EjUKDGxlYWRlckNvbW1pdBgEIAEoA0IR4j8OE
  gxsZWFkZXJDb21taXRSDGxlYWRlckNvbW1pdBIpCghsZWFkZXJJZBgFIAEoCUIN4j8KEghsZWFkZXJJZFIIbGVhZGVySWQSQAoHZ
  W50cmllcxgGIAMoCzIYLnJhZnQudHJhbnNwb3J0LkxvZ0VudHJ5QgziPwkSB2VudHJpZXNSB2VudHJpZXMiaAoTUmVxdWVzdFZvd
  GVSZXNwb25zZRIdCgR0ZXJtGAEgASgDQgniPwYSBHRlcm1SBHRlcm0SMgoLdm90ZUdyYW50ZWQYAiABKAhCEOI/DRILdm90ZUdyY
  W50ZWRSC3ZvdGVHcmFudGVkIvcBChVBcHBlbmRFbnRyaWVzUmVzcG9uc2USJgoHc3VjY2VzcxgBIAEoCEIM4j8JEgdzdWNjZXNzU
  gdzdWNjZXNzEh0KBHRlcm0YAiABKANCCeI/BhIEdGVybVIEdGVybRI+Cg9jdXJyZW50TG9nSW5kZXgYAyABKANCFOI/ERIPY3Vyc
  mVudExvZ0luZGV4Ug9jdXJyZW50TG9nSW5kZXgSMgoLY29tbWl0SW5kZXgYBCABKANCEOI/DRILY29tbWl0SW5kZXhSC2NvbW1pd
  EluZGV4EiMKBm5vZGVJZBgFIAEoCUIL4j8IEgZub2RlSWRSBm5vZGVJZDLHAQoLUmFmdFNlcnZpY2USWAoLUmVxdWVzdFZvdGUSI
  i5yYWZ0LnRyYW5zcG9ydC5SZXF1ZXN0Vm90ZVJlcXVlc3QaIy5yYWZ0LnRyYW5zcG9ydC5SZXF1ZXN0Vm90ZVJlc3BvbnNlIgASX
  goNQXBwZW5kRW50cmllcxIkLnJhZnQudHJhbnNwb3J0LkFwcGVuZEVudHJpZXNSZXF1ZXN0GiUucmFmdC50cmFuc3BvcnQuQXBwZ
  W5kRW50cmllc1Jlc3BvbnNlIgBCEgoOcmFmdC50cmFuc3BvcnRQAWIGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}