// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package raft.transport

@SerialVersionUID(0L)
final case class RequestVoteResponse(
    term: _root_.scala.Long = 0L,
    voteGranted: _root_.scala.Boolean = false,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[RequestVoteResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = term
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, __value)
        }
      };
      
      {
        val __value = voteGranted
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = term
        if (__v != 0L) {
          _output__.writeInt64(1, __v)
        }
      };
      {
        val __v = voteGranted
        if (__v != false) {
          _output__.writeBool(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withTerm(__v: _root_.scala.Long): RequestVoteResponse = copy(term = __v)
    def withVoteGranted(__v: _root_.scala.Boolean): RequestVoteResponse = copy(voteGranted = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = term
          if (__t != 0L) __t else null
        }
        case 2 => {
          val __t = voteGranted
          if (__t != false) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(term)
        case 2 => _root_.scalapb.descriptors.PBoolean(voteGranted)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: raft.transport.RequestVoteResponse.type = raft.transport.RequestVoteResponse
    // @@protoc_insertion_point(GeneratedMessage[raft.transport.RequestVoteResponse])
}

object RequestVoteResponse extends scalapb.GeneratedMessageCompanion[raft.transport.RequestVoteResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[raft.transport.RequestVoteResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): raft.transport.RequestVoteResponse = {
    var __term: _root_.scala.Long = 0L
    var __voteGranted: _root_.scala.Boolean = false
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __term = _input__.readInt64()
        case 16 =>
          __voteGranted = _input__.readBool()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    raft.transport.RequestVoteResponse(
        term = __term,
        voteGranted = __voteGranted,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[raft.transport.RequestVoteResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      raft.transport.RequestVoteResponse(
        term = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        voteGranted = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Boolean]).getOrElse(false)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = RaftProto.javaDescriptor.getMessageTypes().get(4)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = RaftProto.scalaDescriptor.messages(4)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = raft.transport.RequestVoteResponse(
    term = 0L,
    voteGranted = false
  )
  implicit class RequestVoteResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, raft.transport.RequestVoteResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, raft.transport.RequestVoteResponse](_l) {
    def term: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.term)((c_, f_) => c_.copy(term = f_))
    def voteGranted: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.voteGranted)((c_, f_) => c_.copy(voteGranted = f_))
  }
  final val TERM_FIELD_NUMBER = 1
  final val VOTEGRANTED_FIELD_NUMBER = 2
  def of(
    term: _root_.scala.Long,
    voteGranted: _root_.scala.Boolean
  ): _root_.raft.transport.RequestVoteResponse = _root_.raft.transport.RequestVoteResponse(
    term,
    voteGranted
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[raft.transport.RequestVoteResponse])
}
